language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

script:
  - ./gradlew test

after_script:
  - cat core/build/reports/lint-results.xml
  - cat ui/build/reports/lint-results.xml

notifications:
  slack: userfeeds:AsvcCusl8zszBQXwkToCYZzY
